config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts, :projects

  root "home#show", as: "home"

  get "/resume", to: "resume#show", as: 'resume'
  get "/blog", to: "posts#index", as: 'blog'
  get "/portfolio", to: "projects#index", as: 'portfolio'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :projects
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :admin
  has_attached_file :screenshot,  styles: {
    large: ["75%", :jpg],
    original: ["100%", :jpg]
  }
  validates_attachment_content_type :screenshot, content_type: /\Aimage\/.*\z/

  scope :visible, -> { where(visible: true) }
  scope :hidden, -> { where(visible: false) }
  scope :ordered, -> { order(:order) }
  scope :for_display, -> { ordered.visible }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_admin!
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:index]

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:index]

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:show]

  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:index]

  def index
    @projects_for_display = Project.for_display
    @hidden_projects = Project.hidden
  end
  
  def new
    @project = current_admin.projects.new
  end

  def create
    @project = current_admin.projects.new(project_params)
    if @project.save
      flash[:notice] = "The project has been added"
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
    @project = Project.find(params.fetch(:id))
  end

  def edit
    @project = Project.find(params.fetch(:id))
  end

  def update
    @project = Project.find(params.fetch(:id))
    if @project.update(project_params)
      flash[:notice] = "The project has been saved"
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    project = Project.find(params.fetch(:id))
    project.destroy
    redirect_to projects_path
  end

private
  def project_params
    params.require(:project).permit(
      :description,
      :link,
      :order,
      :repository,
      :screenshot,
      :title,
      :visible,
      :year
    )
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:show]

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.erb
<%= render "layouts/navbar" %>

<div id="blog-index">
  <div class="container">
    <h3>Coming Soon</h3>
  </div>
</div>

app/views/home/index.html.erb
<div id="photo-container">
  <div id="photo">
  </div>
</div>

<div id="content-container">
  <p>Hello, I'm Spencer.</p>
  <p>How can I help?</p>
  <br>
  <p><a href="https://www.linkedin.com/in/spencer-alan/" target="_blank" rel="noopener noreferrer">LinkedIn</a></p>
  <p><a href="https://www.github.com/spenceralan/" target="_blank" rel="noopener noreferrer">GitHub</a></p>
</div>

app/views/home/show.html.erb
<div id="home-show">

  <div id="photo-container">
    <div id="photo">
    </div>
  </div>

  <div id="content-container">
    <p>Hello, I'm Spencer.</p>
    <p>How can I help?</p>
    <br>
    <p><%= link_to "Portfolio", portfolio_path %></p>
    <p><%= link_to "Resume", resume_path %></p>
    <p><a href="https://www.linkedin.com/in/spencer-alan/" target="_blank" rel="noopener noreferrer">LinkedIn</a></p>
    <p><a href="https://www.github.com/spenceralan/" target="_blank" rel="noopener noreferrer">GitHub</a></p>
    <p><%= mail_to "hi@spenceralan.com", "Contact", {target: "_blank", rel: "noopener noreferrer"} %></p>
  </div>

</div>

app/views/layouts/_footer.html.erb
<nav class="navbar" id="footer">
  <ul>
    <li><%= link_to "Portfolio", portfolio_path %></li>
    
    <li><%= link_to "Resume", resume_path %></li>
    
    <li><a href="https://www.linkedin.com/in/spencer-alan/" target="_blank" rel="noopener noreferrer">LinkedIn</a></li>
    
    <li><a href="https://www.github.com/spenceralan/" target="_blank" rel="noopener noreferrer">GitHub</a></li>
    
    <li><%= mail_to "hi@spenceralan.com", "Contact", {target: "_blank", rel: "noopener noreferrer"} %></li>
  </ul>

  <p>© 2017 Spencer Alan</p>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-light bg-faded" id="navbar">
  <%= link_to "Spencer Alan", home_path, class: "navbar-brand" %>
  <span class="navbar-text">
    <%= params[:controller].capitalize %>
  </span>
  <% if current_admin %>
    <%= current_admin.email %> | <%= link_to "Sign out", destroy_admin_session_path, method: :delete %>
  <% end %>
</nav>

app/views/layouts/_notices.html.erb
<% if object.present? && object.errors.any? %>
  <div class="notices">
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if notice %>
  <div class="notices">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="notices">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109580269-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-109580269-1');
    </script>

    <title>Spencer Alan</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300', 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "layouts/navbar" %>

<div id="blog-index">
  <%= render "layouts/notices", object: nil %>

  <div class="container">
    <h3>Coming Soon</h3>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="container">
  <%= simple_form_for @project do |f| %>
    <%= f.input :visible %>
    <%= f.input :order %>
    <%= f.input :title %>
    <%= f.input :link %>
    <%= f.input :repository %>
    <%= f.input :year %>
    <%= f.input :description, as: :text %>
    <%= f.input :screenshot, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<%= render "layouts/notices", object: @project %>

<%= render "form" %>

<br>

<div class="container">
  <%= link_to "Delete Project", project_path(@project), method: :delete, class: "btn btn-danger" %>
</div>

app/views/projects/index.html.erb
<%= render "layouts/navbar" %>

<div id="projects-index">
  <div class="container">

    <%= render "layouts/notices", object: nil %>

    <% if current_admin %>
      <%= link_to "New Project", new_project_path %>
    <% end %>

    <% @projects_for_display.each do |project| %>

      <div class="row clearfix">
        <div class="project-image">
          <% if project.screenshot.present? %>
            <%= link_to project.link, target: :blank, rel: "noopener noreferrer" do %>
              <%= image_tag project.screenshot.url(:large) %>
            <% end %>
          <% end %>

          <div class="project-text">
            <h3>
              <%= link_to project.title, project.link, target: :blank, rel: "noopener noreferrer" %>
              <% if current_admin %>
                <%= link_to "Edit", edit_project_path(project) %>
              <% end %>
            </h3>
            <% if project.year.present? %>
              <h4>
                <%= project.year %>
                <% if project.repository.present? %>
                  <%= " - " %>
                  <%= link_to "Repository", project.repository, target: :blank, rel: "noopener noreferrer", title: "Repository" %>
                <% end %>
              </h4>
            <% end %>
            <p><%= project.description %></p>
          </div>
        </div>
      </div>

    <% end %>

    <% if current_admin && @hidden_projects.present? %>
      <br>
      <p>Hidden Projects</p>
      <br>
      <% @hidden_projects.each do |project| %>
        <h3><%= link_to project.title, edit_project_path(project) %></h3>
      <% end %>

    <% end %>

  </div>
</div>

<%= render "layouts/footer"%>

app/views/projects/new.html.erb
<%= render "layouts/notices", object: @project %>

<%= render "form" %>

app/views/resume/show.html.erb
<%= render "layouts/navbar" %>
<div id="resume-show">
  <div class="container">

    <div class="section">
      <h3>About Me</h3>
      <p>I began coding in order to make my work life more efficient. I love solving problems, and Ruby gave me the tools to do it with precision. I generally prefer a simple elegant solution, but at the end of the day I know how to get the job done.</p>
    </div>

    <div class="row justify-content-center">
      <div class="col-4">
        <%= image_tag "ruby.png"%>
      </div>
      <div class="col-4">
        <%= image_tag "cloud.png" %>
      </div>
      <div class="col-4">
          <%= image_tag "chat.png" %>
      </div>
    </div>

    <div class="section row">
      <div class="col-lg-4">
        <h4>Languages</h4>
        <p>Ruby</p>
        <p>JavaScript (ES6)</p>
        <p>Elixir</p>
        <p>SQL</p>
        <p>HTML5 & CSS</p>
      </div>

      <div class="col-lg-4">
        <h4>Frameworks</h4>
        <p>Rails</p>
        <p>Ember</p>
        <p>Angular</p>
        <p>Node.js</p>
      </div>

      <div class="col-lg-4">
        <h4>Skills</h4>
        <p>Passion for Learning</p>
        <p>Interpersonal Communication</p>
        <p>Identifying Process Efficiencies</p>
        <p>Test-Driven Development</p>
        <p>Open Source Contributor</p>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-4"></div>
      <div class="col-4">
        <%= image_tag "gears.png" %>
      </div>
      <div class="col-4"></div>
    </div>

    <div class="section">
      <h3>Relevant Experience</h3>

      <div class="location-position-time">
        <h4>Paydici</h4>
        <p>Development Intern, 2017</p>
      </div>
      <ul>
        <li>
          Developed new, high-quality and fully peer reviewed features to assist staff with daily tasks.
        </li>
        <li>
          Collaborated with engineers and project manager to work on database migrations in MySQL, and maintain the app by triaging and fixing bugs.
        </li>
      </ul>

      <div class="location-position-time">
        <h4>TomKaneArt</h4>
        <p>Developer, 2017</p>
      </div>
      <ul>
        <li>
          Worked with a small team to build a Rails ecommerce website to sell paintings by the Portland artist Tom Kane.
        </li>
        <li>
          Started the process with an initial client meeting to discuss concepts and to learn more about him and his needs. In the design phase, we created templates for the client to interact with and for feedback.
        </li>
        <li>
          Integrated AWS S3 for image storage, Stripe for payment processing, and MailGun for email management, as well as fully encrypting the site with SSL protecting both the owner and visitors.
        </li>
      </ul>

      <div class="location-position-time">
        <h4>Uber</h4>
        <p>Partner Support Representative, 2015 - 2017</p>
      </div>
      <ul>
        <li>
          Took the initiative to write a Ruby program that automated Portland’s daily compliance requirements, thereby saving 250 hours a year.
        </li>
        <li>
          Solicited the company for processes that could be automated and on my own initiative built a Ruby program to automate Seattle’s weekly compliance obligations, saving nearly 1,000 hours of operations work per year.
        </li>
        <li>
          Automated Las Vegas’s daily compliance documentation by writing a Ruby program they could run daily to build the documents they sent to the city. Also reworked their SQL queries that were pulling incomplete and incorrect data.
        </li>
      </ul>

      <div class="location-position-time">
        <h4>Epicodus Chrome Extension</h4>
        <p>Developer, 2017</p>
      </div>
      <ul>
        <li>
          After identifying a pain point of daily lessons at Epicodus, built a Google Chrome extension to assist students with finding the attendance sign in page.
        </li>
        <li>
          Extension was integrated by Epicodus on all their machines in Portland and Seattle and is now a tool students interacts with daily.
        </li>
      </ul>
    </div>

    <div class="row justify-content-center">
      <div class="col-4"></div>
      <div class="col-4">
        <%= image_tag "globe.png" %>
      </div>
      <div class="col-4"></div>
    </div>

    <div class="section">
      <h3>Education</h3>
      <div class="location-position-time">
        <h4>Epicodus</h4>
        <p>Ruby on Rails, 2017</p>
      </div>

      <div class="location-position-time">
        <h4>California State University, Long Beach</h4>
        <p>B.A. Religious Studies, 2010</p>
      </div>
    </div>

  </div>
</div>

<%= render "layouts/footer"%>